"""Generate the skill manifest used by frozen builds — REQ-29, REQ-33.

Skill discovery walks the filesystem, which works from source and does not work
once PyInstaller has packed the modules into an archive. Two attempts at reading
PyInstaller's own module table failed (the attribute is private and moved
between versions), so discovery is made deterministic instead: the module list
is computed here, from the same filesystem walk, and written into the package as
data.

REQ-33 still holds — adding a skill needs no router change and no manifest edit,
because this runs at build time and rediscovers everything.

Run directly, or let installer/kai-backend.spec call it.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
SKILLS = PROJECT / "backend" / "app" / "skills"
MANIFEST = SKILLS / "_manifest.py"
SKIP = {"base", "registry", "_manifest"}

HEADER = '''"""Generated by installer/generate_manifest.py — do not edit.

The list of skill modules, computed at build time so that frozen builds can
find them without walking a filesystem that no longer exists. Regenerated on
every build; from source the registry walks the packages directly and ignores
this.
"""

MODULES = [
'''


def discover() -> list[str]:
    modules: list[str] = []
    for path in sorted(SKILLS.rglob("*.py")):
        if path.stem in SKIP or path.stem == "__init__":
            continue
        relative = path.relative_to(SKILLS).with_suffix("")
        modules.append("app.skills." + ".".join(relative.parts))
    return modules


def write(modules: list[str]) -> Path:
    body = "".join(f'    "{name}",\n' for name in modules)
    MANIFEST.write_text(HEADER + body + "]\n", encoding="utf-8")
    return MANIFEST


def main() -> int:
    if not SKILLS.is_dir():
        print(f"No skills package at {SKILLS}", file=sys.stderr)
        return 1

    modules = discover()
    if not modules:
        print("Found no skill modules — refusing to write an empty manifest.", file=sys.stderr)
        return 1

    write(modules)
    print(f"Wrote {MANIFEST.relative_to(PROJECT)} with {len(modules)} modules")
    for name in modules:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
